site_name: MotiiStudyReport

site_url: https://github.com/motii8128/motii_lib
repo_url: https://github.com/motii8128/motii_lib
edit_uri: https://github.com/motii8128/motii_lib
docs_dir: ./docs
copyright: Copyright &copy; 2023 motii8128

theme:
  name: material
  featuress:
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - announce.dismiss
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    - navigation.sections
    - navigation.tabs
    - navigation.footer
    - navigation.indexes
    - content.tooltips
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
  palette:
    primary: black

plugins:
    - search
    - mermaid2

markdown_extensions:
  - mdx_math
  
extra_javascript: 
  - https://cdn.jsdelivr.net/npm/mathjax@2/MathJax.js?config=TeX-AMS-MML_HTMLorMML
  