site_name: MotiiLib

site_url: https://github.com/motii8128/motii_lib
repo_url: https://github.com/motii8128/motii_lib
edit_uri: https://github.com/motii8128/motii_lib
docs_dir: ./docs
copyright: Copyright &copy; 2023 motii8128

theme:
  name: material
  featuress:
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
  palette:
    primary: black